name: "Python Github Action Template"
description: "Get started with Python Github actions"
author: "Stephen Davis"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
