name: "snake-charmer"
description: "Github action for automatically releasing a python package"
author: "Stephen Davis"
inputs:
  event-payload:
    description: "The event payload provided by the github action"
    default: ""
    required: True
  github-token:
    description: "The github token provided by github actions ${{ secrets.GITHUB_TOKEN }}"
    default: ""
    required: True
runs:
  using: "docker"
  image: "Dockerfile"
