name: Publish Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # we can run the latest build on itself,
        - uses: stephend017/pencil-pusher@main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
