name: Release

on:
  pull_request:
    branches: [ main ]
    types: [opened, closed, labeled, unlabeled, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # we can run the latest build on itself,
        - uses: stephend017/snake-charmer@main
          with:
            github_token: ${{ secrets.GH_PAT }}
            event_payload: ${{ toJSON(github.event) }}
